[WIP]- iOS-46
elpassion/el-debate-ios pull request #46
Opened 2017-09-29 10:06 UTC by Drwalcore

Username removal from first screen

2017-09-29 10:06 UTC, Drwalcore commented
![](https://github.trello.services/images/mini-trello-icon.png) [iOS-46](https://trello.com/c/IkvP9LIZ/107-ios-46)

2017-10-04 07:04 UTC, mateuszszklarek requested changes
Minor changes required - apart of that looks good.

2017-10-04 07:04 UTC, mateuszszklarek commented on Sources/Framework/Business Logic/Alerts/AlertConfiguration.swift
> +            lhs.actions == rhs.actions
Probably it could be one-liner, please check it.

2017-10-04 07:04 UTC, mateuszszklarek commented on Sources/Framework/Controllers/CommentController.swift
>              }
Please fix formatting according to below code:

```swift
_ = inputAlertPresenter.prompt(in: self, with: inputAlertConfiguration).always { [weak self] in
    self?.doDismiss()
}
```

2017-10-04 07:35 UTC, Drwalcore commented
I applied changes and run all tests locally. Let's wait for CI build, then we will see if it's mergeable.

2017-10-04 09:23 UTC, mateuszszklarek approved these changes

2017-10-04 09:23 UTC, mateuszszklarek commented on .gitignore
> +
Please add below gitignore, there are still unnecessary comments:

```
## Build generated
build/
DerivedData/

## Various settings
*.pbxuser
!default.pbxuser
*.mode1v3
!default.mode1v3
*.mode2v3
!default.mode2v3
*.perspectivev3
!default.perspectivev3
xcuserdata/
!*.xcworkspace/contents.xcworkspacedata

## Other
*.moved-aside
*.xcuserstate

## Sourcery
default.profraw

## Obj-C/Swift specific
*.hmap
*.ipa
*.dSYM.zip
*.dSYM

## Playgrounds
timeline.xctimeline
playground.xcworkspace

## Packages/
.build/

## CocoaPods
Pods/

## Carthage
Carthage/Build

## fastlane
fastlane/report.xml
fastlane/Preview.html
fastlane/screenshots
fastlane/test_output

## FBSnapshotTestCase
FailureDiffs/

## Deployment scripts
.setup_travis_deployment.sh
.match_key

## AppCode
.idea/
```

2017-10-04 09:24 UTC, merged