[WIP] IOS-47
elpassion/el-debate-ios pull request #48
Opened 2017-10-04 09:41 UTC by Drwalcore

Fix of #47

2017-10-04 09:48 UTC, Drwalcore commented
![](https://github.trello.services/images/mini-trello-icon.png) [iOS - 47](https://trello.com/c/kewMxvOR/111-ios-47)

2017-10-05 08:16 UTC, mateuszszklarek requested changes
Please update gitignore.

2017-10-05 08:16 UTC, mateuszszklarek commented on .gitignore
> +Swift.gitignore
Please remove this line, and paste below gitignore:

```
## Build generated
build/
DerivedData/

## Various settings
*.pbxuser
!default.pbxuser
*.mode1v3
!default.mode1v3
*.mode2v3
!default.mode2v3
*.perspectivev3
!default.perspectivev3
xcuserdata/
!*.xcworkspace/contents.xcworkspacedata

## Other
*.moved-aside
*.xcuserstate

## Sourcery
default.profraw

## Obj-C/Swift specific
*.hmap
*.ipa
*.dSYM.zip
*.dSYM

## Playgrounds
timeline.xctimeline
playground.xcworkspace

## Packages/
.build/

## CocoaPods
Pods/

## Carthage
Carthage/Build

## fastlane
fastlane/report.xml
fastlane/Preview.html
fastlane/screenshots
fastlane/test_output

## FBSnapshotTestCase
FailureDiffs/

## Deployment scripts
.setup_travis_deployment.sh
.match_key

## AppCode
.idea/
```

2017-10-06 11:20 UTC, mateuszszklarek approved these changes
Mergeable 👍

2017-10-06 11:27 UTC, merged